name: GitHub Forks Sync Action
on: 
  workflow_dispatch:
  schedule:
  - cron: "0 13 * * 1"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:

    - name: GitHub Forks Sync Action
    # You may pin to the exact commit or the version.
    # uses: TobKed/github-forks-sync-action@0e6954211b0700763da003e7678907a77f65253c
      uses: TobKed/github-forks-sync-action@v0.2.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Repository name to clone.
        upstream_repository: https://github.com/OWASP/API-Security
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        #target_repository: # optional, default is 
        # Source branch from which changes will be pushed.
        upstream_branch: master
        # Destination branch to push changes.
        target_branch: master
        # Determines if force push is used
        #force: # optional
        # Determines if --tags is used
        #tags: # optional
   
